@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

KanBugTracker *-right-> "1" UniqueBugList
KanBugTracker *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueBugList
UniqueTagList -[hidden]down- UniqueBugList

UniqueTagList *-right-> "*" Tag
UniqueBugList o-right-> Bug

Bug -up-> "*" Tag

Bug *--> Name
Bug *--> State
Bug *--> Description
@enduml
