@startuml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Interface Parser <<Interface>>
Class "{abstract}\nCommand" as Command
Class EditTagCommandParser
Class EditTagCommand
Class EditTagByStateCommand

EditTagCommandParser .up.|> Parser
EditTagCommandParser .right.> EditTagCommand: creates >
EditTagCommand -up-|> Command
EditTagByStateCommand -up-|> EditTagCommand


@enduml
