@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyKanBugTracker <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class KanBugTracker
Class ReadOnlyKanBugTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Bug {
Class Bug
Class Description
Class State
Class Name
Class UniqueBugList
Class Note
Class Priority
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

KanBugTracker .up.|> ReadOnlyKanBugTracker

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" KanBugTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

KanBugTracker *--> "1" UniqueBugList
UniqueBugList o--> "*" Bug
Bug *--> Name
Bug *--> State
Bug *--> Description
Bug *--> Note
Bug *--> Priority
Bug *--> "*" Tag

ModelManager -->"1" Bug : filtered list
@enduml
