@startuml
start
:User executes edit command;
:EditCommandParser
  splits user input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([note is edited])
    :Store new Optional<Note>
         inside editted Bug;
else ([else])
    :Store Optional<Note> from
    original Bug in edited Bug;
endif
:Replace edited Bug
 in KanBugTracker;
stop
@enduml
