@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Interface Parser <<Interface>>
Class "{abstract}\nCommand" as Command
Class SearchCommandParser
Class SearchCommand
Class BugContainsQueryStringPredicate

SearchCommandParser .up.|> Parser
SearchCommandParser .right.> SearchCommand: creates >
SearchCommand -up-|> Command
SearchCommand *--> BugContainsQueryStringPredicate


@enduml
